### ISSUE TITLE
7.2 Changes to Slot-Specific Tier Tokens

### ISSUE THREAD

**Issue by amiyuy** [Kruithne/TransmogTokens#27]
Slot-specific tokens are changing with patch 7.2.  If an item is for a specific slot you can create the tier item for your spec right away without visiting a vendor.

PTR:

-   [Leggings of the Vanquished Champion](http://www.wowhead.com/item=30245/leggings-of-the-vanquished-champion#currency-for) created [Cataclysm Leggings](http://www.wowhead.com/item=30172/cataclysm-leggings) for my Elemental shaman
-   Slot-specific heroic tokens that used to require the token+gear piece at a vendor let you [directly create the heroic item now](http://i.imgur.com/jdevYma.jpg): [Leggings of the Fiery Protector (Heroic)](http://www.wowhead.com/item=71685/leggings-of-the-fiery-protector#currency-for) created [Erupting Volcanic Kilt (Heroic)](http://www.wowhead.com/item=71555/erupting-volcanic-kilt) for my Elemental shaman
-   Non-slot-specific tokens are still required+a gear piece: ie. [Crystalized Firestone](http://i.imgur.com/hM5StHX.jpg), [Protector's Mark of Sanctification](http://i.imgur.com/IwpCGWl.jpg), etc.
-   Vendors still accept the tokens: http://i.imgur.com/I0ZFr8J.jpg
-   I am not sure if you can create the PvP gear from the tokens or not (ie. [Season 2](http://www.wowhead.com/item=32032/merciless-gladiators-ringmail-leggings)), but the vendors still accept them: http://i.imgur.com/ozwI2YX.jpg

**Comment by Kruithne** [comment]
Thanks for the heads up.

I'm assuming this effects all slot-specific tokens across all tiers? I imagine the Season 2 tokens will convert into the PvE items, rather than the PvP ones you can obtain; needs to be confirmed.

**Comment by amiyuy** [comment]
You can see it on the tokens in the Adventure Guide, so that will probably help with checking what all is affected.  The video source I heard about it from said Serpent Shrine Cavern through Seige of Ogrimmar: https://youtu.be/pFFmFYPxzSA?t=8m20s

I unfortunately didn't get duplicate tokens to test with to see about the PvP items, but I have the same suspicion that it will only give PvE items.

**Comment by amiyuy** [comment]
After poking it some more on Live, the things I still want TransmogTokens for:

1. Only give vendor info for stuff the token can't create (ie. S2 PvP).
2. Tell you which spec's appearance you haven't learned.
3. Still give you info for the sets that need it (ICC).

Otherwise a lot of the vendor tooltip info is redundant now.

**Comment by Kruithne** [comment]
I've gone through and pruned the vendor locations from most tiers which have been converted to use the new self-creation system. Despite having removed the most obvious ones, I have opted to leave in some of the tiers that I'm not quite sure on, such as the TBC tiers which have multiple vendors of both PvE and PvP.

In regards to showing which specification you still need the appearance for, this would require a lot of extra manual input which I can't really justify at the moment, given the time it would take and the decline in usage the add-on is seeing since the changes in latest patches.
