### ISSUE TITLE
Tier 10 vendors in Icecrown Citadel raid instance missing from tooltip

### ISSUE THREAD

**Issue by amiyuy** [Kruithne/TransmogTokens#28]
Now that there's a portal from Lich King's throne to the ICC entrance, I suddenly realized there are vendors in the Icecrown Citadel raid for all of the tier gear, which is actually more convenient than visiting Dalaran (altho there's a portal back to there now too!).

As an Alliance:

Yili < Rogue Armor >
Niby the Almighty < Warlock Armor >
Alana Moonstrike < Druid Armor >
Talan Moonstrike < Hunter Armor >
Jedebia < Shaman Armor >
Malfus Grimfrost < Mage Armor >
Scott the Merciful < Priest Armor >
Crusader Halford < Paladin Armor >
Crusader Grimton < Warrior Armor >
Ormus the Penitent < Death Knight Armor >

**Comment by Kruithne** [comment]
Information for Tier 10 tokens dropped in Icecrown Citadel have been updated to show the new vendors located in Light's Hammer. Thanks.
