### ISSUE TITLE
 /camp

### ISSUE THREAD

**Issue by Striding** [Kruithne/TransmogTokens#37]
Just found a bug when typing /camp then pressing Enter, the error pop ups forcing you to logout using the Game Menu window (Esc key)

------------------------------------------------------

Date: 2017-12-01 10:48:08
ID: 1
Error occured in: AddOn: TransmogTokens
Count: 1
Message: Error: AddOn TransmogTokens attempted to call a forbidden function (Logout()) from a tainted execution path.
Debug:
   [C]: Logout()
   ..\FrameXML\ChatFrame.lua:1701: ?()
   ..\FrameXML\ChatFrame.lua:4512: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4180: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4216: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
None
AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  NPCScanOverlay, v7.3.0.1
  AchieveIt, v
  AckisRecipeList, v7.3.0.1
  ACP, vr250 
  AllTheThings, v1.4.3
  Altoholic, vr183
  AngryKeystones, v
  AntiSpamBot, v
  Archy, v7.3.0.2
  ArtifactPathFinder, v1.6.0
  AucAdvanced, v7.5.5724 (TasmanianThylacine)
  AucFilterBasic, v7.5.5724 (TasmanianThylacine)
  AucFilterOutlier, v7.5.5724.5459(7.5/embedded)
  AucMatchUndercut, v7.5.5724.5585(7.5/embedded)
  AucScanData, v7.5.5724 (TasmanianThylacine)
  AucStatHistogram, v7.5.5724 (TasmanianThylacine)
  AucStatiLevel, v7.5.5724 (TasmanianThylacine)
  AucStatPurchased, v7.5.5724 (TasmanianThylacine)
  AucStatSales, v7.5.5724.5598(7.5/embedded)
  AucStatSimple, v7.5.5724 (TasmanianThylacine)
  AucStatStdDev, v7.5.5724 (TasmanianThylacine)
  AucStatWOWEcon, v7.5.5724.5613(7.5/embedded)
  AucUtilAHWindowControl, v7.5.5724.5575(7.5/embedded)
  AucUtilAppraiser, v7.5.5724.5719(7.5/embedded)
  AucUtilAskPrice, v7.5.5724.5599(7.5/embedded)
  AucUtilAutoMagic, v7.5.5724.5686(7.5/embedded)
  AucUtilCompactUI, v7.5.5724.5715(7.5/embedded)
  AucUtilEasyBuyout, v7.5.5724.5576(7.5/embedded)
  AucUtilFixAH, v7.5.5724 (TasmanianThylacine)
  AucUtilItemSuggest, v7.5.5724.5651(7.5/embedded)
  AucUtilPriceLevel, v7.5.5724.5633(7.5/embedded)
  AucUtilScanButton, v7.5.5724.5631(7.5/embedded)
  AucUtilScanFinish, v7.5.5724.5720(7.5/embedded)
  AucUtilScanProgress, v7.5.5724.4979(7.5/embedded)
  AucUtilScanStart, v7.5.5724.5347(7.5/embedded)
  AucUtilSearchUI, v7.5.5724.5721(7.5/embedded)
  AucUtilSimpleAuction, v7.5.5724.5705(7.5/embedded)
  AucUtilVendMarkup, v7.5.5724.4828(7.5/embedded)
  AuraFrames, v1.5.3
  AutoConfirmRoll, v1.1
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, vv7.3.67
  BadBoyCCleaner, vv7.3.0
  BagBrother, v
  Bagnon, v7.3.2
  BeanCounter, v7.5.5724 (TasmanianThylacine)
  BlizzMove, v
  BloodTrader, v2.2
  BonusRollPreview, v70300.44-Release
  ClassOrderHallsComplete, v1.27
  ColorPickerAdvanced, v2.0.0
  ColorPickerPlus, v
  Configator, v5.1.DEV.431(/embedded)
  CoShelper, v1.3
  CrucibleWeight, v18
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  DBMCore, v7.3.7
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DejaCharacterStats, v730rc108
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DialogKey, v1.5.2
  Dominos, v7.2.2
  DominosEncounter, v
  DominosProgress, v
  EasyObliterate, v30
  EasyDeleteConfirm, v
  Een, v1.5.3
  ErrorFilter, vv3.4
  FlashTaskBar, v
  FlightMap, v7.0.0.6
  GarrisonMissionManager, vv55
  GatherMate2, v1.41
  Grid, v7.1.0.1
  GridIndicatorSideIcons, v60200-1
  GridStatusDungeonRole, v1.2.5
  GroupfinderFlags, v0.7
  HandyNotes, vv1.4.15
  HandyNotesArgus, v0.20.0
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesHallowsEnd, vv1.2.5
  HandyNotesLegionClassOrderHalls, vv1.25
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLostAndFound, v1
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarTelemancy, v1
  HandyNotesWitheredChests, v1.2
  HHTD, v2.4.6
  HiddenArtifactTracker, v
  ILDBagnon, v2.0.16 70200
  ILDBlizzard, v2.0.16 70200
  Informant, v7.5.5724 (TasmanianThylacine)
  InspectEquip3, v3.0.9
  InstancePortals, v8
  ItemLevelDisplay, v2.0.16 70200
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LargerMacroIconSelection, vv1.2.1
  LeatrixPlus, v7.3.28
  LFGCallToArmsBroker, v1.0.8
  LibExtraTip, v5.12.DEV.430(/embedded)
  Mapster, v1.7.6
  Masque, v7.3.0
  MasqueCainyx, v4.3.00
  MasterPlan, v0.109.1
  MasterPlanA, vA
  MogIt, v3.8.2
  MogItMail, v3.8.2
  MogItOneHanded, v3.8.2
  MogItOther, v3.8.2
  MogItRanged, v3.8.2
  MogItTwoHanded, v3.8.2
  MoveAnything, v16.3.1
  MythicPlusLoot, v2.1
  NameplateSCT, v1.0
  NeedToKnow, v4.0.26
  NeverExit, v103
  NPCScan, v7.3.0.6
  OgriLazy, v1.3.4
  OmniCC, v7.3
  OPie, vVanilla 1
  ParagonBars, v7.3.0
  Pawn, v2.2.15
  PetTracker, v7.3.0
  PetTrackerBreeds, v7.3.0
  PetTrackerConfig, v7.3.0
  PetTrackerJournal, v7.3.0
  PetTrackerSwitcher, v7.3.0
  PetTrackerUpgrades, v7.3.0
  PokemonTrainer, v7.2.0
  Postal, vv3.5.8
  PreciseWorldQuestTimers, v
  QuestGuru, v2.4.31
  RareScanner, v3.5.1
  RCLootCouncil, v2.7.1
  Rematch, v4.7.8
  RepHelper, v7.3.0.3-release
  SavedInstances, v@project-version@
  ServerHop, v7.3.0.1
  SexyMap, vv7.3.0
  SharedMedia, v3.0.7-188
  Simulationcraft, v1.8.4
  SlideBar, v7.5.5724 (TasmanianThylacine)
  SortedCurrencyTab, v2.1
  StrataFix, v3.5.1
  Stubby, v7.5.5724 (TasmanianThylacine)
  TalkLess, v1.0.3
  TipHelper, v5.12.DEV.405(/embedded)
  TipTac, v17.10.10
  TipTacItemRef, v17.10.10
  TipTacTalents, v17.10.10
  Titan, v5.12.6.70300
  TitanBag, v5.12.6.70300
  TitanClock, v5.12.6.70300
  TitanGold, v5.12.6.70300
  TitanPerformance, v5.12.6.70300
  TitanRepair, v5.12.6.70300
  TitanSocial, v7.3.0
  TitanVolume, v5.12.6.70300
  TomTom, vv70300-1.0.0
  TooltipItemIcon, v1.74
  ToyBoxEnhanced, v1.7
  TransmogTokens, v1.4.8
  TrufiGCD, v
  tullaRange, v7.3.0
  WeakAuras, v2.4.25
  WorldQuestTracker, v
  WoWDBProfiler, v
  Wyr3dIcyVeinsStats, v
  XLoot, v7.3-1
  XLootGroup, v7.3-1
  XLootMaster, v7.3-1
  XLootMonitor, v7.3-1
  ZoneLevelInfo, v2.1.5
  ZPerl, v5.4.6
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v7.3.2.70300 <none>
  (ck=1740)

**Comment by R-Adrian** [comment]
not an error in TransmogTokens.

Logout() is now forbidden to use in macros or addons, it's a protected function since patch 7.3.2 and the error message will blame any random addon that's active.

https://www.wowhead.com/news=274728/undocumented-changes-in-patch-7-3-2

**Comment by Kruithne** [comment]
As @R-Adrian said, this is not directly an issue with TransmogTokens. Because we're listening for command usage, we end up in the execution stack, along with a lot of other add-ons, which causes the execution to be tainted. Once it comes to attempting to call a secure function, `Logout`, it throws an error and blames the first add-on in the stack.
