### ISSUE TITLE
WoWUp.io support

### ISSUE THREAD

**Issue by Tyrama** [Kruithne/TransmogTokens#45]
Hi, since this project seems to be updated here but not on curseforge could you add a release repo? Would be greatly appreciated!

From WoWUp: GitHub import requires addons to have a built release within the repo (ie github.com/addon_name/releases. If the URL only contains source zip files it will not import. You or the addon author will need to build a release in the github repo so that it can import.

**Comment by Kruithne** [comment]
Hey,

I've created a release for the repository containing the latest version of the add-on based on the source from the repository. I can't confirm if the version actually works or not as I haven't had the time to test it.

Let me know if there are any issues with it.
